### ISSUE TITLE
benchmark过吗

### ISSUE THREAD

**Issue by chuangyou** [eahydra/swnet#2]
benchmark过吗

**Comment by eahydra** [comment]
用这个包写过一个程序，用来测试产品中的一个服务端（C++代码），其中有一项业务是读取磁盘。
当时是在我的笔记本上跑这个测试程序，网卡是千兆，运行的系统是WINDOWS 8，对端服务器是网卡万兆，链接万兆交换机，CPU是至强E5，运行的系统是WINDOWS 2008。

速度平均跑到80MB/S。

这个库其实是GO下idiom，一个goroutine去recv，一个goroutine去send，或者在发送者自己的goroutine中发送。这两种方式我都测试过，性能基本一致。另外这个包还要求使用者自己实现自己的协议序列化，而我测试中用到协议是https://github.com/eahydra/goproto这个协议生成器生成的代码。

**Comment by chuangyou** [comment]
你这个配置跑多少万长连，广播消耗如何，系统稳定性，CPU内存等资源的消耗情况呢

**Comment by eahydra** [comment]
这个说来忏愧，我写的GO的代码都没有用于产品中，因为我参与的产品都是C/C++开发。
你可以看下代码，基本上没什么花哨的东西，都是GO本身常用的实现方法。
你可以自己用GO根据自己的需求实现后测试和剖析。
