### ISSUE TITLE
the doubt about useing “127.0.0.1” as address of server 

### ISSUE THREAD

**Issue by 29206394** [eahydra/swnet#4]
开发环境：云主机具备公共IP：2.2.2.2(假设)
1.建立server时，address使用localhost:9999，此时使用客户端连接2.2.2.2:9999时连接失败；
1.建立server时，address使用2.2.2.2:9999，此时使用客户端连接2.2.2.2:9999时连接成功；

请问这是go标准库net的机制么，可否详细解释一下，多谢

**Comment by eahydra** [comment]
我在我自己的阿里云ECS上试了下，不存在这个问题啊。
go的 net库里也没有这类限制。你看下是否是你防火墙或者路由表之类的问题？

**Comment by 29206394** [comment]
大意了，配置问题
多谢
